/* M8 — File upload / download helpers.
 *
 * Phase-1 mock: uploadFile() reads the file as a base64 string and stores
 * it in the FileMetaStore so the UI can show "uploaded" + preview. No real
 * server. downloadAs() generates an in-browser blob and triggers a download
 * for receipts / discharge summaries / payslips. Phase-2 swap: uploadFile
 * → presigned POST to S3 / Blob; downloadAs unchanged.
 */

export interface UploadResult {
  id: string
  filename: string
  size: number
  mime: string
  uploadedAt: string
  /** Object URL — valid for this session only. */
  url: string
}

/** Upload a single File from an <input type=file>. Async because real-world swap will be. */
export async function uploadFile(file: File): Promise<UploadResult> {
  // Use createObjectURL so the UI can render the file (image preview, anchor href).
  const url = typeof URL !== 'undefined' && URL.createObjectURL ? URL.createObjectURL(file) : ''
  return {
    id: `FILE-${Date.now()}-${Math.floor(Math.random() * 9999)}`,
    filename: file.name,
    size: file.size,
    mime: file.type || 'application/octet-stream',
    uploadedAt: new Date().toISOString(),
    url,
  }
}

/** Trigger a browser download of a Blob with the given filename. */
export function downloadAs(filename: string, blob: Blob): void {
  if (typeof document === 'undefined') return
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  setTimeout(() => {
    a.remove()
    URL.revokeObjectURL(url)
  }, 0)
}

/** Convenience: download a UTF-8 text file (CSV, TXT, etc.). */
export function downloadText(filename: string, text: string, mime = 'text/plain'): void {
  downloadAs(filename, new Blob([text], { type: mime }))
}

/** Convenience: build a minimal printable HTML page and trigger print/save. */
export function printableHtml(title: string, bodyHtml: string): void {
  if (typeof window === 'undefined') return
  const w = window.open('', title, 'width=700,height=900')
  if (!w) return
  w.document.write(`<!doctype html><html><head><title>${title}</title>
<style>
  body { font-family: 'Helvetica', 'Arial', sans-serif; padding: 32px; color: #0f172a; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  h2 { font-size: 14px; margin: 0; color: #64748b; font-weight: 400; }
  .hdr { display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 2px solid #0f172a; padding-bottom: 12px; margin-bottom: 18px; }
  table { width: 100%; border-collapse: collapse; margin: 10px 0 16px; }
  th, td { padding: 8px 6px; text-align: left; border-bottom: 1px solid #e2e8f0; font-size: 13px; }
  th { font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; color: #64748b; }
  .total { font-weight: 700; font-size: 16px; }
  .ftr { margin-top: 36px; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; }
</style>
</head><body>
${bodyHtml}
<div class="ftr">System-generated by Umang HIMS · ${new Date().toLocaleString('en-IN')}</div>
</body></html>`)
  w.document.close()
  setTimeout(() => { try { w.print() } catch { /* ignore */ } }, 250)
}
