"use client"

import Link from "next/link"
import { toast } from "sonner"
import {
  Receipt, CreditCard, CheckCircle2, Clock, ShieldCheck, Download,
  Stethoscope, ClipboardList, BedDouble, ArrowRight,
} from "lucide-react"
import { useAuthStore } from "@/store/useAuthStore"
import { usePatientOrdersStore, acceptedItems, lineTotal, orderTotal } from "@/store/usePatientOrdersStore"
import { cn } from "@/lib/utils"
import { printableHtml } from "@/lib/fileIO"

function downloadReceipt(admission: { id: string; date: string; title: string; insurer: string; total: number; covered: number }) {
  const coPay = admission.total - admission.covered
  const html = `
    <div class="info-row">
      <div class="info-item"><span class="info-label">Patient</span><span class="info-value">Kiran Patil</span></div>
      <div class="info-item"><span class="info-label">Patient ID</span><span class="info-value">PT-20394</span></div>
      <div class="info-item"><span class="info-label">Invoice No.</span><span class="info-value">${admission.id}</span></div>
      <div class="info-item"><span class="info-label">Date</span><span class="info-value">${admission.date}</span></div>
      <div class="info-item"><span class="info-label">Visit</span><span class="info-value">${admission.title}</span></div>
    </div>
    <h3>Billing Summary</h3>
    <table><thead><tr><th>Description</th><th style="text-align:right">Amount (₹)</th></tr></thead><tbody>
      <tr><td>Total hospital charges</td><td style="text-align:right">${admission.total.toLocaleString('en-IN')}</td></tr>
      <tr><td>Insurance covered · ${admission.insurer}</td><td style="text-align:right">− ${admission.covered.toLocaleString('en-IN')}</td></tr>
      <tr class="total"><td>Patient co-pay (paid)</td><td style="text-align:right">₹${coPay.toLocaleString('en-IN')}</td></tr>
    </tbody></table>
    <p class="muted">Tax invoice — system-generated by Umang HIMS.</p>`
  printableHtml(admission.id, html)
}

function downloadBillReceipt(title: string, total: number, lines: { desc: string; amount: number }[]) {
  const html = `
    <h3>Charges</h3>
    <table><thead><tr><th>Description</th><th style="text-align:right">Amount (₹)</th></tr></thead><tbody>
      ${lines.map((l) => `<tr><td>${l.desc}</td><td style="text-align:right">${l.amount.toLocaleString('en-IN')}</td></tr>`).join('')}
      <tr class="total"><td>Total</td><td style="text-align:right">₹${total.toLocaleString('en-IN')}</td></tr>
    </tbody></table>`
  printableHtml(title, html)
}

const today = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })

// A previous cashless admission — illustrates the insurance / co-pay split.
const ADMISSION = {
  id: 'INV-IPD-2026-044',
  date: '14 Mar 2026',
  title: 'Inpatient admission · Cardiac evaluation',
  insurer: 'Star Health',
  total: 48500,
  covered: 43650, // ~90% cashless approved
}

export default function PatientBilling() {
  const currentUser = useAuthStore(s => s.currentUser)
  const { items, doctor, received, paid } = usePatientOrdersStore()

  const kept = acceptedItems(items)
  const ordersTotal = orderTotal(items)
  const ordersOutstanding = received && !paid ? ordersTotal : 0
  const coPay = ADMISSION.total - ADMISSION.covered

  const name = currentUser?.name ?? 'Patient'
  const pid = currentUser?.id ?? 'PT-00000'

  return (
    <div className="max-w-3xl mx-auto pb-10 space-y-5">
      <div>
        <h1 className="text-[24px] font-bold text-slate-900 tracking-tight">Billing &amp; Payments</h1>
        <p className="text-[13px] text-slate-500 mt-1">{name} · {pid}</p>
      </div>

      {/* Summary tiles */}
      <div className="grid grid-cols-3 gap-3">
        <div className="rounded-2xl bg-white shadow-[0_1px_4px_rgba(15,23,42,0.06),0_8px_28px_rgba(15,23,42,0.05)] p-4">
          <p className="text-[12px] text-slate-400 font-semibold">Billed this visit</p>
          <p className="text-[20px] font-bold text-slate-900 mt-0.5">₹{500 + (received ? ordersTotal : 0)}</p>
        </div>
        <div className="rounded-2xl bg-white shadow-[0_1px_4px_rgba(15,23,42,0.06),0_8px_28px_rgba(15,23,42,0.05)] p-4">
          <p className="text-[12px] text-slate-400 font-semibold">Insurance covered</p>
          <p className="text-[20px] font-bold text-[#0E7490] mt-0.5">₹{ADMISSION.covered.toLocaleString('en-IN')}</p>
        </div>
        <div className="rounded-2xl bg-white shadow-[0_1px_4px_rgba(15,23,42,0.06),0_8px_28px_rgba(15,23,42,0.05)] p-4">
          <p className="text-[12px] text-slate-400 font-semibold">Outstanding</p>
          <p className={cn("text-[20px] font-bold mt-0.5", ordersOutstanding > 0 ? "text-amber-600" : "text-green-600")}>₹{ordersOutstanding}</p>
        </div>
      </div>

      {/* Consultation fee — paid at check-in */}
      <BillCard
        icon={<Stethoscope className="h-5 w-5 text-[#0E7490]" />} tint="bg-[rgba(14,116,144,0.07)]"
        id={`INV-OPD-${new Date().getFullYear()}-118`} date={`${today} · paid at check-in`}
        title="OPD Consultation" status="paid"
        lines={[{ desc: `Consultation — ${doctor}`, amount: 500 }]}
        footer="Paid by UPI at check-in"
      />

      {/* Doctor's orders bill — second payment moment */}
      {received && (
        <BillCard
          icon={<ClipboardList className="h-5 w-5 text-[#0E7490]" />} tint="bg-[rgba(14,116,144,0.07)]"
          id={`INV-RX-${new Date().getFullYear()}-118`} date={`${today} · prescribed by ${doctor}`}
          title="Doctor's orders — tests & medicines" status={paid ? 'paid' : 'pending'}
          lines={kept.map(i => ({ desc: `${i.name}${i.kind === 'medicine' ? ` × ${i.qty}` : ''}`, amount: lineTotal(i) }))}
          footer={paid ? 'Paid — tests booked & medicines sent to pharmacy' : undefined}
          payHref="/patient/orders"
        />
      )}

      {/* Cashless admission — insurance split */}
      <div className="rounded-3xl bg-white shadow-[0_1px_4px_rgba(15,23,42,0.06),0_8px_28px_rgba(15,23,42,0.05)] p-5">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-3">
            <span className="h-10 w-10 rounded-2xl bg-rose-50 flex items-center justify-center flex-shrink-0"><BedDouble className="h-5 w-5 text-rose-600" /></span>
            <div>
              <p className="text-[15px] font-bold text-slate-900">{ADMISSION.title}</p>
              <p className="text-[12px] text-slate-500 flex items-center gap-1"><Clock className="h-3 w-3" /> {ADMISSION.id} · {ADMISSION.date}</p>
            </div>
          </div>
          <span className="text-[12px] font-bold px-2.5 py-1 rounded-full bg-green-50 text-green-700 flex-shrink-0">✓ Settled</span>
        </div>

        {/* Cashless split */}
        <div className="rounded-2xl bg-slate-50 p-4 space-y-2.5">
          <div className="flex items-center justify-between text-[13px]">
            <span className="text-slate-500">Total hospital bill</span>
            <span className="font-semibold text-slate-900">₹{ADMISSION.total.toLocaleString('en-IN')}</span>
          </div>
          <div className="flex items-center justify-between text-[13px]">
            <span className="text-[#0E7490] flex items-center gap-1.5"><ShieldCheck className="h-4 w-4" /> Cashless approved · {ADMISSION.insurer}</span>
            <span className="font-semibold text-[#0E7490]">− ₹{ADMISSION.covered.toLocaleString('en-IN')}</span>
          </div>
          <div className="border-t border-slate-200 pt-2.5 flex items-center justify-between">
            <span className="text-[13px] font-bold text-slate-900">Your co-pay (paid)</span>
            <span className="text-[15px] font-bold text-slate-900">₹{coPay.toLocaleString('en-IN')}</span>
          </div>
          {/* coverage bar */}
          <div className="h-2 rounded-full bg-slate-200 overflow-hidden">
            <div className="h-full bg-[rgba(14,116,144,0.07)]0 rounded-full" style={{ width: `${Math.round((ADMISSION.covered / ADMISSION.total) * 100)}%` }} />
          </div>
          <p className="text-[11.5px] text-slate-400">{Math.round((ADMISSION.covered / ADMISSION.total) * 100)}% covered by your insurer · {100 - Math.round((ADMISSION.covered / ADMISSION.total) * 100)}% co-pay</p>
        </div>

        <button onClick={() => downloadReceipt(ADMISSION)} className="mt-4 w-full bg-slate-100 text-slate-700 font-bold text-[13.5px] rounded-xl py-2.5 flex items-center justify-center gap-2 active:scale-[0.98] transition cursor-pointer">
          <Download className="h-4 w-4" /> Download receipt & claim documents
        </button>
      </div>
    </div>
  )
}

type Line = { desc: string; amount: number }
function BillCard({
  icon, tint, id, date, title, status, lines, footer, payHref,
}: {
  icon: React.ReactNode; tint: string; id: string; date: string; title: string
  status: 'paid' | 'pending'; lines: Line[]; footer?: string; payHref?: string
}) {
  const total = lines.reduce((s, l) => s + l.amount, 0)
  return (
    <div className={cn("rounded-3xl bg-white shadow-[0_1px_4px_rgba(15,23,42,0.06),0_8px_28px_rgba(15,23,42,0.05)] p-5", status === 'pending' && "ring-1 ring-amber-200")}>
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-3">
          <span className={cn("h-10 w-10 rounded-2xl flex items-center justify-center flex-shrink-0", tint)}>{icon}</span>
          <div>
            <p className="text-[15px] font-bold text-slate-900">{title}</p>
            <p className="text-[12px] text-slate-500 flex items-center gap-1"><Clock className="h-3 w-3" /> {id} · {date}</p>
          </div>
        </div>
        <span className={cn("text-[12px] font-bold px-2.5 py-1 rounded-full flex-shrink-0", status === 'paid' ? 'bg-green-50 text-green-700' : 'bg-amber-50 text-amber-600')}>
          {status === 'paid' ? '✓ Paid' : 'Pending'}
        </span>
      </div>

      <div className="rounded-2xl bg-slate-50 p-4 space-y-2">
        {lines.map((l, i) => (
          <div key={i} className="flex justify-between text-[13px]">
            <span className="text-slate-500">{l.desc}</span>
            <span className="font-semibold text-slate-800">₹{l.amount}</span>
          </div>
        ))}
        <div className="border-t border-slate-200 pt-2 flex justify-between font-bold">
          <span className="text-slate-900">Total</span>
          <span className="text-[#0E7490]">₹{total}</span>
        </div>
      </div>

      {status === 'paid' ? (
        <div className="mt-3 flex items-center justify-between gap-2">
          <span className="text-[12.5px] text-green-700 flex items-center gap-1.5"><CheckCircle2 className="h-4 w-4" /> {footer ?? 'Payment successful'}</span>
          <button onClick={() => downloadBillReceipt(title, total, lines)} className="text-[12.5px] font-semibold text-slate-600 flex items-center gap-1.5 hover:text-slate-900 cursor-pointer"><Download className="h-3.5 w-3.5" /> Receipt</button>
        </div>
      ) : (
        <Link href={payHref ?? '#'} className="mt-3 w-full bg-[#0E7490] text-white font-bold text-[14px] rounded-xl py-2.5 flex items-center justify-center gap-2 active:scale-[0.98] transition">
          <CreditCard className="h-4.5 w-4.5" /> Review &amp; pay ₹{total} <ArrowRight className="h-4 w-4" />
        </Link>
      )}
    </div>
  )
}
