import type { AuditLogEntry } from '@/types/cmo'

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600000).toISOString()
const minsAgo  = (m: number) => new Date(Date.now() - m * 60000).toISOString()

export const seedAuditLog: AuditLogEntry[] = [
  { id: 'au_001', timestamp: minsAgo(5),    user: 'Dr. Rajesh Sharma', userRole: 'CMO', action: 'Alert Acknowledged',   target: 'Alert alt_006 — O₂ plant down CH Kolar',     details: 'Marked as acknowledged', ip: '192.168.1.10', facility: 'CH Kolar' },
  { id: 'au_002', timestamp: minsAgo(18),   user: 'Dr. Rajesh Sharma', userRole: 'CMO', action: 'Approval Signed',      target: 'Approval apv_005 — Leave Dr. Patel',          details: 'Approved with note: "Replacement arranged"', ip: '192.168.1.10' },
  { id: 'au_003', timestamp: minsAgo(34),   user: 'Dr. Rajesh Sharma', userRole: 'CMO', action: 'Login',                target: 'CMO Cockpit',                                details: 'Session started', ip: '192.168.1.10' },
  { id: 'au_004', timestamp: hoursAgo(1),   user: 'System',            userRole: 'Auto', action: 'Alert Created',        target: 'Alert alt_001 — O₂ critical Hamidia',         details: 'Auto-generated by supply monitoring', ip: 'System' },
  { id: 'au_005', timestamp: hoursAgo(1.5), user: 'Dr. Mehta',         userRole: 'BMO', action: 'Alert Assigned',        target: 'Alert alt_003 — Maternal death Berasia',      details: 'Assigned to Dr. Mehta for death audit', ip: '192.168.1.22', facility: 'CHC Berasia' },
  { id: 'au_006', timestamp: hoursAgo(2),   user: 'Dr. Rajesh Sharma', userRole: 'CMO', action: 'Transfer Initiated',   target: 'Patient Lata Bai — CHC Berasia → Hamidia DH', details: 'Emergency referral approved', ip: '192.168.1.10' },
  { id: 'au_007', timestamp: hoursAgo(2.5), user: 'Dr. Rajesh Sharma', userRole: 'CMO', action: 'Approval Rejected',    target: 'Approval apv_007 — PIP Reallocation',         details: 'Rejected: requires finance committee approval first', ip: '192.168.1.10' },
  { id: 'au_008', timestamp: hoursAgo(3),   user: 'System',            userRole: 'Auto', action: 'Alert Created',        target: 'Alert alt_005 — Paracetamol stockout',        details: 'Triggered by daily inventory sync', ip: 'System' },
  { id: 'au_009', timestamp: hoursAgo(3.5), user: 'Dr. Rajesh Sharma', userRole: 'CMO', action: 'Field Visit Logged',   target: 'Facility: CHC Berasia',                      details: 'Surprise inspection — 3 findings logged', ip: '192.168.1.10', facility: 'CHC Berasia' },
  { id: 'au_010', timestamp: hoursAgo(4),   user: 'Store Keeper',      userRole: 'Pharmacy', action: 'Indent Raised',   target: 'Indent apv_009 — Surgical gloves Hamidia',   details: 'Sent for CMO approval', ip: '192.168.2.30', facility: 'Hamidia DH' },
  { id: 'au_011', timestamp: hoursAgo(5),   user: 'Dr. Rajesh Sharma', userRole: 'CMO', action: 'Broadcast Sent',       target: 'All BMOs — Dengue advisory',                 details: 'Message: "Activate dengue containment in urban wards"', ip: '192.168.1.10' },
  { id: 'au_012', timestamp: hoursAgo(6),   user: 'System',            userRole: 'Auto', action: 'Alert Created',        target: 'Alert alt_006 — O₂ plant down CH Kolar',     details: 'Equipment downtime alert triggered', ip: 'System', facility: 'CH Kolar' },
  { id: 'au_013', timestamp: hoursAgo(7),   user: 'Dr. Rajesh Sharma', userRole: 'CMO', action: 'Report Signed',         target: 'Weekly IHIP Return — W25 2026',              details: 'Digital signature applied, submitted to state portal', ip: '192.168.1.10' },
  { id: 'au_014', timestamp: hoursAgo(8),   user: 'HR Cell',           userRole: 'HR', action: 'Posting Created',        target: 'Posting apv_008 — Staff Nurse CHC Bairagarh', details: 'Joining order issued', ip: '192.168.1.40' },
  { id: 'au_015', timestamp: hoursAgo(10),  user: 'Dr. Rajesh Sharma', userRole: 'CMO', action: 'Alert Escalated',       target: 'Alert alt_002 — Dengue cluster',             details: 'Escalated to District Collector and State IDSP', ip: '192.168.1.10' },
  { id: 'au_016', timestamp: hoursAgo(12),  user: 'Finance Cell',      userRole: 'Finance', action: 'PIP Reallocation Proposed', target: 'PIP JSY → NCD ₹2.4L',          details: 'Proposal submitted for CMO approval', ip: '192.168.1.50' },
  { id: 'au_017', timestamp: hoursAgo(14),  user: 'Dr. Rajesh Sharma', userRole: 'CMO', action: 'Login',                target: 'CMO Cockpit',                                details: 'Session started — previous day', ip: '192.168.1.10' },
  { id: 'au_018', timestamp: hoursAgo(16),  user: 'IDSP Module',       userRole: 'System', action: 'Surveillance Alert', target: 'Dengue cluster Ward 14/17/19',               details: 'Threshold exceeded: 3.2× baseline', ip: 'System', facility: 'Bhopal Urban' },
  { id: 'au_019', timestamp: hoursAgo(18),  user: 'Dr. Rajesh Sharma', userRole: 'CMO', action: 'Approval Signed',      target: 'apv_003 — Transfer Dr. Verma',               details: 'Emergency transfer approved', ip: '192.168.1.10' },
  { id: 'au_020', timestamp: hoursAgo(20),  user: 'Dr. Rajesh Sharma', userRole: 'CMO', action: 'Staff Explanation Demanded', target: '12 AWOL doctors',                    details: 'SMS notices sent via HRMS', ip: '192.168.1.10' },
  ...Array.from({ length: 30 }, (_, i) => ({
    id: `au_${String(i + 21).padStart(3, '0')}`,
    timestamp: hoursAgo(22 + i * 3),
    user: ['Dr. Rajesh Sharma', 'System', 'BMO Berasia', 'Store Keeper', 'HR Cell', 'Finance Cell'][i % 6],
    userRole: ['CMO', 'Auto', 'BMO', 'Pharmacy', 'HR', 'Finance'][i % 6],
    action: ['Alert Acknowledged', 'Report Generated', 'Indent Raised', 'Transfer Approved', 'Login', 'Approval Signed'][i % 6],
    target: `System event ${i + 21}`,
    details: 'Routine operation logged',
    ip: '192.168.1.10',
  })),
]
